### ISSUE TITLE
Curse words database

### ISSUE THREAD

**Issue by xxzefgh** [bumbeishvili/GeoWordsDatabase#2]
Do you have any idea how to extract just curse words from this database? Or does it contain them at all?

**Comment by bumbeishvili** [comment]
I don't think you can . Words are grouped just by books, they are extracted from . 

On high level you can categorize these words (Medicine,Jurisprudence, Hagiography e.t.c ) , but you can't extract only curse words ... 

If you will be able to collect it, Please open PR for it :)

**Comment by xxzefgh** [comment]
So only way is to categorize them by hand 😑 If I manage to do anything, it will be open source btw.

Thanks.
